title: "Karin Vardy"
theme: jekyll-theme-minimal
title_align: center
description: "I'm a PhD student at the [Peles group](https://www.weizmann.ac.il/mcb/peles/) I'm interested in biology of myelinating glia cells"


