title: "Karin Vardy"
theme: jekyll-theme-minimal
title_align: right
description: "Biology of Myelinating Glia"
logo: "downloads/logo.jpeg" 
<img src="assets/logo.jpeg" alt="Circular Image" width="100" height="100">


